<<<<<<< HEAD
spring.application.name=microservices-1
server.port=8081
=======
spring.application.name=service-registory
server.port=8761
eureka.client.register-with-eureka=false 
eureka.client.fetch-registry=false  
>>>>>>> 784251bc47986daed27caf47c0c373206d976116
